(load "1.43.scm")
(define (smooth f)
  (define dx 0.00001)
  (lambda (x) (/ (+ (f x)
                    (f (- x dx))
                    (f (+ x dx)))
                 3)))
(define (n-fold-smooth f n)
  (repeated smooth n))
