;(load "fixed-point.scm")
(load "1.46.scm")
(load "1.43.scm")
(define (average x y) (/ (+ x y) 2.0))
(define (average-damp f)
  (lambda (x) (average x (f x))))
(define (fixed-point-of-transform g transform guess)
  (fixed-point (transform g) guess))
(define (nth-roots n x)
  (define (cal-k i)
    (if (< n (expt 2 (+ i 1)))
      i
      (cal-k (+ i 1))))
  (fixed-point-of-transform (lambda (y) (/ x (expt y (- n 1))))
                  (repeated average-damp (cal-k 1))
                  1.0))
